### PR TITLE
Added static all-contributors line.

### PR DESCRIPTION
**Pull request by taml**
This is my first ever pull request. I'm hoping I've understood the issue and implemented the static line correctly!

### CODE REVIEW

**Comment by mbad0la** [comment]
Hey @taml , Thank you for taking up this!  
So, there are few things to add to this and then we'll be good to go.
- Update the package behaviour shown in README.md, adding this static line to the package boilerplate example and the snippet code.
- Update the example GIF in README.md ( optional )

Also, there is an extension to adding this functionality perfectly. As in your implementation, the functionality is snippet triggered. So if a person doesn't use the snippet, we'd like this static line to be rendered everytime the user presses `ctrl+atl+p` as well. Would you like to give that a try too?

**Comment by taml** [comment]
Thanks for the further instruction! I've updated README.md, and hopefully implemented the static line in the right way for keyboard shortcut generation by adding it to the strList array!

**Comment by mbad0la** [comment]
@taml it won't work by just adding the line to the strList array. The strList array items arn't used to render the static lines. They are just used as a comparision with the text-buffer to identify which line numbers contain those static lines.  
We'll take up this added functionality in another PR. For now, roll-back on your changes to `allcontributors.coffee`. I'll merge your PR. Thanks for your time. :)

**Comment by taml** [comment]
Perhaps a little out of my knowledge depth at the moment then haha! Thanks for your time and for letting me participate!

**Comment by mbad0la** [comment]
@taml, if you are interested I can point you to some revelant information so that you could finish it up in a different PR?  
I just want to round this up because adding this behaviour on the code needs the knowledge of the [Atom API](https://atom.io/docs/api/v1.7.2/AtomEnvironment) and CoffeeScript, which in my opinion is way too much work for any first pull request. :P  
Hoping you continue contributing to the community ( and probably on our projects :P ). All the best. :)

**Comment by taml** [comment]
I can definitely have a look and see if it's something I can manage, I've mastered some JavaScript basics so CoffeeScript won't be a completely foreign language to me and I have only been using Atom for about 3 weeks so I'm not familiar with the API just yet, but maybe it will make sense with more instruction!

Thanks for making my first contribution experience a good one :) , I look forward to contributing more!

**Comment by mbad0la** [comment]
@taml Have a look at the our code. You will find some Atom API methods in it. I guess it would be beneficial if you could find out those methods and read it's [documentation](https://atom.io/docs/api/v1.7.2/TextEditor) from the official Atom API docs. I suppose once to get to know how to modify the text on the active editor through the API, we can figure out a way to add the static line through code.  
Don't hesitate to ping us if you need any help. :)

**Comment by taml** [comment]
I've had a little look through the code and documentation, I've spotted two methods that might allow for adding the code 'editor.insertText('Hello World')' and 'editor.setText('String')' so I'm not sure if it will be as simple as adding one of these in the right place with the static line inserted? Probably not haha! I've noticed you've used setTextInBufferRange in the code so I'm hoping I'm getting just a little closer to a solution with this!

**Comment by mbad0la** [comment]
Yes...you are. You'd also need the line number of an existing static line. So the text buffer which would be overwritten would be between `<!-- Contributors START` and `This project follows the [all-contributors](https://github.com/kentcdodds/all-contributors) specification.`, if the line already exists (happens if you initialised it with the snippet or you used the keymap previously). And if the line doesn't exist the buffer that needs to be overwritten would be between `<!-- Contributors START` and `<!-- Contributors table END -->` (for backward compatibility or if the boilerplate wasn't initialised with the snippet and the user left out the static line while manually setting up the boilerplate)  
I hope I'm making sense :P  
Also, as this PR is closed, make further comments on the issue #6  as it is open and hence easily accessible to anyone wanting to be a part of the discussion.

**Pull request merged**
